# Generated by Django 3.1.3 on 2020-11-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnoutapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileModel',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='chartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='burnoutapp.profilemodel')),
            ],
        ),
    ]
